//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAchievement
    {
        public System.Guid ID { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public System.Guid Achievement_id { get; set; }
        public Nullable<byte> Verified { get; set; }
        public System.Guid Classgroup_id { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual Classgroup Classgroup { get; set; }
    }
}
