//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achievement> Achievements { get; set; }
        public DbSet<Achievement_type> Achievement_type { get; set; }
        public DbSet<Classgroup> Classgroups { get; set; }
        public DbSet<Contest_result> Contest_result { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<GroupAchievement> GroupAchievements { get; set; }
        public DbSet<Level_type> Level_type { get; set; }
        public DbSet<Organisator> Organisators { get; set; }
        public DbSet<Point_exceptiontable> Point_exceptiontable { get; set; }
        public DbSet<Point_maintable> Point_maintable { get; set; }
        public DbSet<Regulation> Regulations { get; set; }
        public DbSet<Regulation_Role> Regulation_Role { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Semestr> Semestrs { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentAchievement> StudentAchievements { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User_client> User_client { get; set; }
        public DbSet<UserEvent> UserEvents { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
