//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classgroup
    {
        public Classgroup()
        {
            this.GroupAchievements = new HashSet<GroupAchievement>();
            this.Students = new HashSet<Student>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int Students_count { get; set; }
        public Nullable<System.Guid> Mainstudent_id { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<GroupAchievement> GroupAchievements { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual Student MainStudent { get; set; }
    }
}
