//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_client
    {
        public User_client()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.UserEvents = new HashSet<UserEvent>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Pass_hash { get; set; }
        public Nullable<System.Guid> Student_id { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserEvent> UserEvents { get; set; }
    }
}
