//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level_type
    {
        public Level_type()
        {
            this.Achievement = new HashSet<Achievement>();
            this.Point_maintable = new HashSet<Point_maintable>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Achievement> Achievement { get; set; }
        public virtual ICollection<Point_maintable> Point_maintable { get; set; }
    }
}
