//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Achievement
{
    public Achievement()
    {
        this.Point_exceptiontable = new HashSet<Point_exceptiontable>();
        this.StudentAchievements = new HashSet<StudentAchievement>();
        this.GroupAchievements = new HashSet<GroupAchievement>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> Start_date { get; set; }
    public Nullable<System.DateTime> End_date { get; set; }
    public Nullable<System.Guid> Level_type_id { get; set; }
    public System.Guid Achievement_type_id { get; set; }
    public Nullable<byte> Verified { get; set; }
    public Nullable<System.Guid> Organisator_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public System.Guid Achievement_typeID { get; set; }

    public virtual Organisator Organisator { get; set; }
    public virtual ICollection<Point_exceptiontable> Point_exceptiontable { get; set; }
    public virtual ICollection<StudentAchievement> StudentAchievements { get; set; }
    public virtual ICollection<GroupAchievement> GroupAchievements { get; set; }
    public virtual Achievement_type Achievement_type { get; set; }
    public virtual Level_type Level_type { get; set; }
}

public partial class Achievement_type
{
    public Achievement_type()
    {
        this.Achievement = new HashSet<Achievement>();
        this.Point_maintable = new HashSet<Point_maintable>();
        this.Point_exceptiontable = new HashSet<Point_exceptiontable>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Achievement> Achievement { get; set; }
    public virtual ICollection<Point_maintable> Point_maintable { get; set; }
    public virtual ICollection<Point_exceptiontable> Point_exceptiontable { get; set; }
}

public partial class Classgroup
{
    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public int Students_count { get; set; }
    public System.Guid Mainstudent_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Student Student { get; set; }
}

public partial class Contest_result
{
    public Contest_result()
    {
        this.Point_exceptiontable = new HashSet<Point_exceptiontable>();
        this.Point_maintable = new HashSet<Point_maintable>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Point_exceptiontable> Point_exceptiontable { get; set; }
    public virtual ICollection<Point_maintable> Point_maintable { get; set; }
}

public partial class Event
{
    public Event()
    {
        this.UserEvents = new HashSet<UserEvent>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<UserEvent> UserEvents { get; set; }
}

public partial class GroupAchievement
{
    public System.Guid ID { get; set; }
    public int Count { get; set; }
    public Nullable<System.DateTime> Start_date { get; set; }
    public Nullable<System.DateTime> End_date { get; set; }
    public System.Guid Achievement_id { get; set; }
    public Nullable<byte> Verified { get; set; }
    public System.Guid Group_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Achievement Achievement { get; set; }
}

public partial class Level_type
{
    public Level_type()
    {
        this.Achievement = new HashSet<Achievement>();
        this.Point_maintable = new HashSet<Point_maintable>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Achievement> Achievement { get; set; }
    public virtual ICollection<Point_maintable> Point_maintable { get; set; }
}

public partial class Organisator
{
    public Organisator()
    {
        this.Achievements = new HashSet<Achievement>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Achievement> Achievements { get; set; }
}

public partial class Point_exceptiontable
{
    public System.Guid ID { get; set; }
    public int Points { get; set; }
    public System.Guid Achievement_id { get; set; }
    public Nullable<System.Guid> Contest_result_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Achievement Achievement { get; set; }
    public virtual Contest_result Contest_result { get; set; }
    public virtual Achievement_type Achievement_type { get; set; }
}

public partial class Point_maintable
{
    public System.Guid ID { get; set; }
    public int Points { get; set; }
    public Nullable<System.Guid> Level_type_id { get; set; }
    public System.Guid Achievement_type_id { get; set; }
    public Nullable<System.Guid> Contest_result_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public System.Guid Achievement_typeID { get; set; }

    public virtual Achievement_type Achievement_type { get; set; }
    public virtual Level_type Level_type { get; set; }
    public virtual Contest_result Contest_result { get; set; }
}

public partial class Regulation
{
    public Regulation()
    {
        this.Regulation_Role = new HashSet<Regulation_Role>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Regulation_Role> Regulation_Role { get; set; }
}

public partial class Regulation_Role
{
    public System.Guid ID { get; set; }
    public System.Guid Regulation_id { get; set; }
    public System.Guid Role_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Regulation Regulation { get; set; }
    public virtual Role Role { get; set; }
}

public partial class Role
{
    public Role()
    {
        this.Regulation_Role = new HashSet<Regulation_Role>();
        this.UserRoles = new HashSet<UserRole>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Regulation_Role> Regulation_Role { get; set; }
    public virtual ICollection<UserRole> UserRoles { get; set; }
}

public partial class Semestr
{
    public System.Guid ID { get; set; }
    public System.DateTime Start_date { get; set; }
    public string End_date { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
}

public partial class Student
{
    public Student()
    {
        this.Classgroups = new HashSet<Classgroup>();
        this.StudentAchievements = new HashSet<StudentAchievement>();
        this.User_client = new HashSet<User_client>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string Studbook_number { get; set; }
    public System.Guid Group_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual ICollection<Classgroup> Classgroups { get; set; }
    public virtual ICollection<StudentAchievement> StudentAchievements { get; set; }
    public virtual ICollection<User_client> User_client { get; set; }
}

public partial class StudentAchievement
{
    public System.Guid ID { get; set; }
    public string Amazon_link { get; set; }
    public System.Guid Achievement_id { get; set; }
    public System.Guid Student_id { get; set; }
    public Nullable<System.Guid> Contest_result_id { get; set; }
    public Nullable<byte> Verified { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Achievement Achievement { get; set; }
    public virtual Student Student { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
}

public partial class User_client
{
    public User_client()
    {
        this.UserRoles = new HashSet<UserRole>();
        this.UserEvents = new HashSet<UserEvent>();
    }

    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Pass_hash { get; set; }
    public Nullable<System.Guid> Student_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Student Student { get; set; }
    public virtual ICollection<UserRole> UserRoles { get; set; }
    public virtual ICollection<UserEvent> UserEvents { get; set; }
}

public partial class UserEvent
{
    public System.Guid ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Description { get; set; }
    public System.Guid User_Client_id { get; set; }
    public System.Guid Event_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Event Event { get; set; }
    public virtual User_client User_client { get; set; }
}

public partial class UserRole
{
    public System.Guid ID { get; set; }
    public System.Guid User_Client_id { get; set; }
    public System.Guid Role_id { get; set; }
    public string user_created { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }

    public virtual Role Role { get; set; }
    public virtual User_client User_client { get; set; }
}
