//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Regulation_Role = new HashSet<Regulation_Role>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Regulation_Role> Regulation_Role { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
