//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAchievement
    {
        public System.Guid ID { get; set; }
        public string Amazon_link { get; set; }
        public System.Guid Achievement_id { get; set; }
        public System.Guid Student_id { get; set; }
        public Nullable<System.Guid> Contest_result_id { get; set; }
        public Nullable<byte> Verified { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual Student Student { get; set; }
    }
}
